### ISSUE TITLE
rename to couchdb-calculate-session-id?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/couchdb-calculate-session-id#5]
I feel like the name might be a bit confusing. "generate" might imply that we randomly generate a session id, but in fact the result is always the same based on the input.

I think calling it `couchdb-calculate-session-id` would make that more clear.

**Comment by gr2m** [comment]
This is how a `couchdb-validate-session-id` method could look like :v:

``` js
module.exports = validateSessionId

var calculateSessionId = require('couchdb-calculate-session-id')
var base64url = require("base64url")

function validateSessionId(sessionId, serverSecret, findUserDoc) {
  parts = base64url.decode(sessionId).split(':')
  var username = parts[0]
  var timestamp = parseInt(parts[1], 16)
  if (timestamp * 1000 < Date.now()) {
    return Promise.reject(new Error('expired'))
  }

  return findUserDoc(username)
  .then(function(doc) {
    if (sessionId === calculateSessionId(username, doc.salt, secret, timestamp)) {
      // session is valid
    } else {
      throw new Error('invalid')
    }
  })
}
```

**Comment by kxepal** [comment]
How about just `couchdb-session-id` with methods: `validate` || `verify`, `generate` || `new` ? Short, clear and simple.

**Comment by gr2m** [comment]
small npm modules are the best, I'd make two separate ones :) sorry for putting the distraction with putting `couchdb-validate-session-id` in this thread, I had to put this somewhere so I don’t forget :) Was late yesterday

Shall we rename couchdb-generate-session-id to couchdb-calculate-session-id or not?

**Comment by gr2m** [comment]
from [Hoodie Chat](http://hood.ie/chat)

<img width="673" alt="screen shot 2015-12-13 at 10 32 42" src="https://cloud.githubusercontent.com/assets/39992/11767740/deedbd68-a184-11e5-8520-16a0875de815.png">

**Comment by gr2m** [comment]
renamed it: https://www.npmjs.com/package/couchdb-calculate-session-id
